Only send the signal if the pid is a positive value.
greenbone/openvas pull request #593
Opened 2020-08-28 14:54 UTC by jjnicola

**What**:
Only send the signal if the pid is a positive value.

**Why**:
Since kb_item_get_int() will return -1 if the key does
not exist. killing -1 pid will send the signal system wide.
Apparently the stop signal is received twice, being the second one
sent by a child process, but received after the kb was already cleaned up.
Therefore -1 is received and the kill SIGUSR1 signal reaches other process.

**How**:
You can test this starting 2 or 3 parallel scans with many hosts. This produces a big amount child process which during stops scans, spread the kill signal to other process. You should be able to stop the scans without problem if this patch is applied.

**Checklist**:

- [ ] Tests
- [x] [CHANGELOG](https://github.com/greenbone/openvas/blob/master/CHANGELOG.md) Entry

2020-08-28 19:45 UTC, cfi-gb requested changes

2020-08-28 19:45 UTC, cfi-gb commented on CHANGELOG.md
> +- Only send the signal if the pid is a positive value.[#593](https://github.com/greenbone/openvas/pull/593)
```suggestion
- Only send the signal if the pid is a positive value. [#593](https://github.com/greenbone/openvas/pull/593)
```

2020-08-28 19:45 UTC, cfi-gb commented on src/openvas.c
> +     since kb_item_get_int() will return -1 if the key does
```suggestion
     Since kb_item_get_int() will return -1 if the key does
```

2020-08-31 06:55 UTC, ArnoStiefvater approved these changes

2020-08-31 06:57 UTC, ArnoStiefvater approved these changes

2020-08-31 07:36 UTC, cfi-gb approved these changes

2020-08-31 07:36 UTC, merged