Add insert_tcp_options() nasl function
greenbone/openvas pull request #618
Opened 2020-11-06 12:09 UTC by jjnicola

**What**:
This add support for inserting MSS, Wscale, sack permit and timestamp
tcp options.

**Why**:
It was not supported and was required.

**How**:
Run the nasl script below, and check with tcpdump or wireshark that the options are set as expected.
```
if(description) {
  script_oid("1.2.3");
  exit(0);
}

include("misc_func.inc");

myhost = this_host();
port = 22022;
srcport= 35000;
dstip = get_host_ip();
filter = string("tcp and src ", dstip, " and dst ", myhost, " and dst port ", srcport, " and src port ", port);

ip = forge_ip_packet(ip_v   : 4,
                     ip_hl  : 5,
                     ip_tos : 0,
                     ip_len : 20,
                     ip_id  : rand(),
                     ip_p   : IPPROTO_TCP,
                     ip_ttl : 255,
                     ip_off : 0,
                     ip_src : myhost,
                     ip_dst: dstip);

tcp = forge_tcp_packet(ip       : ip,
                       th_ack   : 0,
                       th_dport : port,
                       th_flags : TH_SYN,
                       #th_seq   : tcp_seq + 1024,
                       th_sport : srcport,
                       th_x2    : 0,
                       th_off   : 5,
                       th_win   : 1024,
                       th_urp   : 0,
                       data:"H");
tcp = insert_tcp_options(tcp:tcp, 2, 1024, 3, 14 , 4);

r = send_packet(tcp, pcap_active:TRUE, pcap_filter:filter);

```

**Checklist**:

- [ ] Tests
- [ ] [CHANGELOG](https://github.com/greenbone/openvas/blob/master/CHANGELOG.md) Entry

2020-11-10 07:26 UTC, cfi-gb requested changes

2020-11-10 07:26 UTC, cfi-gb commented on nasl/nasl_packet_forgery.c
> +              nasl_perror (lexic, "%s: Invalid value for TCP option MSS'\n",
```suggestion
              nasl_perror (lexic, "%s: Invalid value for TCP option MSS\n",
```

2020-11-10 07:26 UTC, cfi-gb commented on nasl/nasl_packet_forgery.c
> +              nasl_perror (lexic, "%s: Invalid value for TCP option WScale'\n",
```suggestion
              nasl_perror (lexic, "%s: Invalid value for TCP option WScale\n",
```

2020-11-10 07:26 UTC, cfi-gb commented on nasl/nasl_packet_forgery.c
> +            nasl_perror (lexic, "%s: Invalid value for TCP option Timestamp'\n",
```suggestion
            nasl_perror (lexic, "%s: Invalid value for TCP option Timestamp\n",
```

2020-11-10 07:26 UTC, cfi-gb commented on nasl/nasl_packet_forgery_v6.c
> +              nasl_perror (lexic, "%s: Invalid value for TCP option MSS'\n",
```suggestion
              nasl_perror (lexic, "%s: Invalid value for TCP option MSS\n",
```

2020-11-10 07:26 UTC, cfi-gb commented on nasl/nasl_packet_forgery_v6.c
> +              nasl_perror (lexic, "%s: Invalid value for TCP option WScale'\n",
```suggestion
              nasl_perror (lexic, "%s: Invalid value for TCP option WScale\n",
```

2020-11-10 07:26 UTC, cfi-gb commented on nasl/nasl_packet_forgery_v6.c
> +            nasl_perror (lexic, "%s: Invalid value for TCP option Timestamp'\n",
```suggestion
            nasl_perror (lexic, "%s: Invalid value for TCP option Timestamp\n",
```

2020-11-10 07:26 UTC, cfi-gb commented on nasl/nasl_packet_forgery.c
> + *   TCPOPT_SACK_PERMITTED (4), no value requiered.
```suggestion
 *   TCPOPT_SACK_PERMITTED (4), no value required.
```

2020-11-10 07:26 UTC, cfi-gb commented on nasl/nasl_packet_forgery_v6.c
> + *   TCPOPT_SACK_PERMITTED (4), no value requiered.
```suggestion
 *   TCPOPT_SACK_PERMITTED (4), no value required.
```

2020-11-10 08:24 UTC, ArnoStiefvater commented on nasl/nasl_packet_forgery.c
> +                         + 20); /* ip->ip_hl is bogus, we work around that */
The formatting is bad here. Maybe put the comment above the line so the formatter does not do this.

2020-11-10 08:24 UTC, ArnoStiefvater commented on nasl/nasl_packet_forgery.c
> +    return NULL;
opts need to be freed here I guess.

2020-11-10 08:24 UTC, ArnoStiefvater commented on nasl/nasl_packet_forgery.c
> +  bzero (&pseudoheader, sizeof (pseudoheader));
bzero and bcopy are deprecated. memset and memcpy should be used instead.

2020-11-10 08:24 UTC, ArnoStiefvater commented on nasl/nasl_packet_forgery.c
> +  bzero (&pseudoheader, sizeof (pseudoheader));
bzero and bcopy are deprecated. memset and memcpy should be used instead. Same for all following occurrences.

2020-11-16 07:29 UTC, ArnoStiefvater approved these changes
Tested with the supplied scripts and tcpdump. Everything works as expected.

2020-11-16 08:32 UTC, cfi-gb approved these changes

2020-11-16 08:33 UTC, cfi-gb commented
Reviewed the fixes to my review and approved them (only them, not the whole code changes here which i can't approve).

2020-11-16 08:36 UTC, merged