Add get_tcp_option() nasl function.
greenbone/openvas pull request #621
Opened 2020-11-09 16:09 UTC by jjnicola

**What**:

**Why**:

**How**:

**Checklist**:

- [ ] Tests
- [ ] [CHANGELOG](https://github.com/greenbone/openvas/blob/master/CHANGELOG.md) Entry

2020-11-09 16:10 UTC, jjnicola commented
Depends on #618

2020-11-17 10:25 UTC, ArnoStiefvater requested changes

2020-11-17 10:25 UTC, ArnoStiefvater commented on nasl/nasl_packet_forgery.c
> + * @param[in] option  Option to get.
maybe add where to get a list of supported options like `see insert_tcp_options()`.

2020-11-17 10:25 UTC, ArnoStiefvater commented on nasl/nasl_packet_forgery_v6.c
> +      if (options_len > 5) // Options presents
```suggestion
      if (options_len > 5) // Options present
```

2020-11-17 10:25 UTC, ArnoStiefvater commented on nasl/nasl_packet_forgery_v6.c
> + * @param[in] option  Option to get.
Same as above. add where to find the available options.

2020-11-17 10:25 UTC, ArnoStiefvater commented on nasl/nasl_packet_forgery.c
> +      if (tcp->th_off > 5) // Options presents
```suggestion
      if (tcp->th_off > 5) // Options present
```

2020-11-17 10:25 UTC, ArnoStiefvater commented on nasl/nasl_packet_forgery.c
> +      nasl_perror (lexic, "get_tcp_element: No valid 'tcp' argument\n");
get_tcp_option. best use compiler `__func__` .
Same for ipv6 function.

2020-11-17 10:36 UTC, ArnoStiefvater commented on nasl/nasl_packet_forgery.c
> +          if (tcp_all_options != NULL)
The formatting of the output is wrong here. the value should come after the `:`. And would be nice to have them all aligned similar to the elements above. Same for ipv6 version.

2020-11-17 14:02 UTC, ArnoStiefvater approved these changes

2020-11-18 11:31 UTC, cfi-gb requested changes
I hope i got all comments / suggestions correct but you should see the point that the logging should be done consistently.

2020-11-18 11:31 UTC, cfi-gb commented on nasl/nasl_packet_forgery.c
> +                   "Usage: get_tcp_option (tcp:tcp, option: TCPOPT_MAXSEG)",
`get_tcp_option` probably should be `__func__` as well?

Also note the difference between tcp:tcp (no space) vs. option: TCPOPT_MAXSEG (space after the :).

2020-11-18 11:31 UTC, cfi-gb commented on nasl/nasl_packet_forgery_v6.c
> +                   "Usage: get_tcp_option (tcp:tcp, option: TCPOPT_MAXSEG)",
`get_tcp_option` probably should be `__func__` as well? If not it should be at least `get_tcp_v6_option`.

Also note the difference between `tcp:tcp` (no space) vs. `option: TCPOPT_MAXSEG` (space after the `:`).

2020-11-18 11:31 UTC, cfi-gb commented on nasl/nasl_packet_forgery.c
> +      nasl_perror (lexic, "%s: Invalid value for TCP option Timestamp'\n",
```suggestion
      nasl_perror (lexic, "%s: Invalid value for TCP option 'Timestamp'.\n",
```

2020-11-18 11:31 UTC, cfi-gb commented on nasl/nasl_packet_forgery_v6.c
> +      nasl_perror (lexic, "%s: Invalid value for TCP option Timestamp'\n",
```suggestion
      nasl_perror (lexic, "%s: Invalid value for TCP option Timestamp\n",
```

2020-11-18 11:31 UTC, cfi-gb commented on nasl/nasl_packet_forgery_v6.c
> +      nasl_perror (lexic, "%s: No options\n", __func__);
```suggestion
      nasl_perror (lexic, "%s: No TCP options found in passed TCP packet.\n", __func__);
```

2020-11-18 11:31 UTC, cfi-gb commented on nasl/nasl_packet_forgery.c
> +      nasl_perror (lexic, "%s: No options\n", __func__);
```suggestion
      nasl_perror (lexic, "%s: No TCP options found in passed TCP packet.\n", __func__);
```

2020-11-18 11:31 UTC, cfi-gb commented on nasl/nasl_packet_forgery_v6.c
> +          g_debug ("%s: Unsupported %u tcp option. "
```suggestion
          g_debug ("%s: Unsupported %u TCP option. "
```

2020-11-18 11:31 UTC, cfi-gb commented on nasl/nasl_packet_forgery.c
> +          g_debug ("%s: Unsupported %u tcp option. "
```suggestion
          g_debug ("%s: Unsupported %u TCP option. "
```

2020-11-18 11:31 UTC, cfi-gb commented on nasl/nasl_packet_forgery.c
> + * @return  Integer or array given the case..
```suggestion
 * @return  Integer or array given the case.
```

2020-11-18 11:31 UTC, cfi-gb commented on nasl/nasl_packet_forgery_v6.c
> +                   "%s: No options\n."
```suggestion
                   "%s: No 'option' argument passed but required.\n"
```

2020-11-18 11:31 UTC, cfi-gb commented on nasl/nasl_packet_forgery_v6.c
> +                   "Not all options are returned",
```suggestion
                   "Not all options are returned.",
```

2020-11-18 11:31 UTC, cfi-gb commented on nasl/nasl_packet_forgery.c
> +      nasl_perror (lexic, "%s: No valid 'tcp' argument\n", __func__);
```suggestion
      nasl_perror (lexic, "%s: No valid 'tcp' argument passed.\n", __func__);
```

2020-11-18 11:31 UTC, cfi-gb commented on nasl/nasl_packet_forgery.c
> +                   "Not all options are returned",
```suggestion
                   "Not all options are returned.",
```

2020-11-18 11:31 UTC, cfi-gb commented on nasl/nasl_packet_forgery_v6.c
> +      nasl_perror (lexic, "%s: No valid 'tcp' argument\n", __func__);
```suggestion
      nasl_perror (lexic, "%s: No valid 'tcp' argument passed.\n", __func__);
```

2020-11-18 11:31 UTC, cfi-gb commented on nasl/nasl_packet_forgery_v6.c
> +  ipsz = get_var_size_by_name (lexic, "tcp");
Shouldn't this be moved a little bit down once it is required? There are a few checks like `if (packet == NULL)` which are exiting earlier without accessing ipsz.

2020-11-18 11:31 UTC, cfi-gb commented on nasl/nasl_packet_forgery.c
> +  ipsz = get_var_size_by_name (lexic, "tcp");
Shouldn't this be moved a little bit down once it is required? There are a few checks like `if (packet == NULL)` which are exiting earlier without accessing ipsz.

2020-11-20 13:04 UTC, cfi-gb approved these changes
Approving the updates to my suggestions. Thanks :+1:

2020-11-23 06:15 UTC, ArnoStiefvater approved these changes

2020-11-23 06:16 UTC, merged