End the scanner in a better way if the host list is malformed.
greenbone/openvas pull request #625
Opened 2020-11-20 12:41 UTC by jjnicola

**What**:
End the scanner in a better way if the host list is malformed and send a message to the client in case of invalid target list

**Why**:
If the target host list is not empty but malformed, the hosts struct is NULL. Then gvm_hosts_resolve() segfaults

**How**:
Start a scan with gvm-cli (gsa already checks for malformed target) wiht 192.168.0.1/32 as host target.

**Checklist**:

- [ ] Tests
- [ ] [CHANGELOG](https://github.com/greenbone/openvas/blob/master/CHANGELOG.md) Entry

2020-11-20 12:58 UTC, bjoernricks reviewed
Would it be possible to include the invalid target list in the error message for the client too?

2020-11-23 06:34 UTC, ArnoStiefvater requested changes

2020-11-23 06:34 UTC, ArnoStiefvater commented on src/attack.c
> +      sprintf (buf, "Invalid target list: %s.", hostlist);
Buffer is very small (only 96 bytes) and `hostlist` can get very big. Use `snprinf` or `g_snprintf()` and a bigger buffer if its likely that hostlist will exceed 96 bytes length. You can use `strlen` to get the needed lenght and check it agains the buffer size.
Do we even limit the lenght of a hoststring?

2020-11-23 06:34 UTC, ArnoStiefvater commented on src/attack.c
> +      message_to_client (main_kb, buf, NULL, NULL, "ERRMSG");
`message_to_client` has internal buffer with len 2048. Make sure that no buffer overflow can happen in this function  too.

2020-11-23 08:50 UTC, ArnoStiefvater approved these changes
g_strdup_printf is a good solution.

2020-11-23 08:51 UTC, merged