Add drop_privileges_user for fork()ed processes
greenbone/openvas pull request #634
Opened 2021-01-06 15:45 UTC by jjnicola

**What**:
Add new scanner only option drop_privileges_user.
Extend nasl_pread() to accept a new argument drop_privileges. The new argument receive a user which will become the owner of the fork()ed process. 

**Why**:
To allow spawning a process with a different process uid. Normally, openvas runs as root privileges and this allows to drop privileges

**How**:
- Add drop_privileges_user = <some-user> to openvas.conf
- Run a script which uses pread() nasl function passing the drop_privileges argument.
- Check that the process owner is the desired.

**Checklist**:

- [ ] Tests
- [ ] [CHANGELOG](https://github.com/greenbone/openvas/blob/master/CHANGELOG.md) Entry

2021-01-06 20:48 UTC, cfi-gb requested changes

2021-01-06 20:48 UTC, cfi-gb commented on nasl/nasl_cmd_exec.c
> + * @param[in] cmd Command to be run.
```suggestion
 * @param[in] cmd Command to run.
```

2021-01-06 20:48 UTC, cfi-gb commented on nasl/nasl_cmd_exec.c
> + * @param[in] drop_privileges Owner of the spawned process.
The name `drop_privileges` for the parameter sounds more like one which accepts a TRUE/FALSE, not a user as a string. Maybe something like e.g. the following could make sense:

```suggestion
 * @param[in] drop_privileges_user Owner of the spawned process.
```

2021-01-06 20:48 UTC, cfi-gb commented on nasl/nasl_cmd_exec.c
> + * @return The content of stderr or stdout written by the spawn process or Null
```suggestion
 * @return The content of stderr or stdout written by the spawn process or NULL.
```

2021-01-08 10:19 UTC, cfi-gb requested changes

2021-01-08 10:19 UTC, cfi-gb commented on src/utils.c
> +      || !strcmp (pref, "drop_privileges_user")
Please add a man page entry for this new preference to https://github.com/greenbone/openvas/blob/master/doc/openvas.8.in

I'm also quite unhappy about the naming of this new preferences for the following reason:

There is also the existing `drop_privileges` preference (one line above) which is (if enabled) dropping the privileges of the whole `openvas` process. Due to the fact that `NULL` is passed to the `drop_privileges` here:

https://github.com/greenbone/openvas/blob/c84f5bd9780eeb96e2792c22ef6b7693d178344f/src/nasl_plugins.c#L243

the user `nobody` is always chosen:

https://github.com/greenbone/gvm-libs/blob/80b1e370b2e23d44ca8b43ff9bac0ef60b3eacf3/base/drop_privileges.c#L57

But due to the similarity of the naming for both preferences one might think that `drop_privileges_user` is the user which is used if `drop_privileges` is enabled which is not the case. In addition both preferences have a similar naming but are doing two completely different things:

- `drop_privileges` is dropping the privileges for the whole `openvas` process to `nobody`
- `drop_prvileges_user` is used in a single NASL function to drop the privileges to the specific user independent of the `drop_privileges` preferences

Currently i don't have a better suggestion for the naming but maybe some one of @greenbone/gvm-dev has some suggestions? If not let us discuss this next week.

2021-01-11 13:13 UTC, cfi-gb requested changes

2021-01-11 13:13 UTC, cfi-gb commented on CHANGELOG.md
> +- Add new scanner only option for spawinng processes with a different owner. [#634](https://github.com/greenbone/openvas/pull/634)
```suggestion
- Add new scanner only option for spawning NASL functions with a different owner. [#634](https://github.com/greenbone/openvas/pull/634)
```

2021-01-11 13:13 UTC, cfi-gb commented on doc/openvas.8.in
> +If this preference is set to 'yes, openvas-scanner will attempt to drop its
```suggestion
If this preference is set to 'yes', OpenVAS will attempt to drop its
```

2021-01-11 13:13 UTC, cfi-gb commented on doc/openvas.8.in
> +root privilege before launching any NVT and the new process owner is 'nobody';
```suggestion
root privilege before launching any VT and the new process owner is 'nobody';
```

2021-01-11 13:13 UTC, cfi-gb commented on doc/openvas.8.in
> +enabled, this option should not be used, as drop_privileges sets the owner to
```suggestion
enabled, this option should not be used, as 'drop_privileges' sets the owner to
```

2021-01-11 13:13 UTC, cfi-gb commented on doc/openvas.8.in
> +If a user is set, some nasl function can use this user to drop its root privilege.
```suggestion
If a user is set, NASL functions can use this user to drop its root privilege.
```

2021-01-11 13:13 UTC, cfi-gb commented on doc/openvas.8.in
> +This preference must not be mixed with 'drop_privileges'. If drop privileges is
```suggestion
This preference must not be mixed with 'drop_privileges'. If 'drop_privileges' is
```

2021-01-11 13:19 UTC, cfi-gb commented on nasl/nasl_cmd_exec.c
> + * @param[in] drop_privileges_user Owner of the spawned process.
```suggestion
 * @param[in] cd If set to TRUE the scanner will change it's current directory to the directory where the command was found.
```

2021-01-11 15:00 UTC, jjnicola commented on nasl/nasl_cmd_exec.c
> + * @param[in] cd If set to TRUE the scanner will change it's current directory to the directory where the command was found.
```suggestion
 * @param[in] cd If set to TRUE the scanner will change it's current directory
 * to the directory where the command was found.
```

2021-01-11 15:16 UTC, cfi-gb reviewed
Text / comment changes looks good and i'm approving these with this comment.

Final testing and approval needs to be done by a @greenbone/gvm-dev member.

2021-01-11 15:20 UTC, ArnoStiefvater approved these changes

2021-01-11 15:21 UTC, merged